Document: call-forward
Title: Debian call-forward Manual
Author: <insert document author here>
Abstract: This manual describes what call-forward is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/call-forward/call-forward.sgml.gz

Format: postscript
Files: /usr/share/doc/call-forward/call-forward.ps.gz

Format: text
Files: /usr/share/doc/call-forward/call-forward.text.gz

Format: HTML
Index: /usr/share/doc/call-forward/html/index.html
Files: /usr/share/doc/call-forward/html/*.html
